version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - node/install-packages:
          check-cache: detect
      - run:
          name: build
          command:  "yarn run build-ghpages"
      - persist_to_workspace:
          root: ~/project
          paths:
            - out

  test:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - node/install-packages:
          check-cache: detect
      - run:
          name: Run tests
          command: yarn run test

  deploy:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Disable jekyll builds
          command: touch out/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install gh-pages --save-dev
            git config user.email "susiyanti.g11@gmail.com"
            git config user.name "susiyanti"
      - add_ssh_keys:
          fingerprints:
            - "26:64:a3:ea:72:67:93:83:2d:b9:73:9a:53:03:70:0f"
      - run:
          name: Deploy to gh-pages branch
          command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d out'

workflows:
  build-test-approval-deploy:
    jobs:
      - build
      - test
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: beta           
      - deploy:
          requires:
            - hold
