version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command:  "next build && next export"
  request-approval:
    type: approval
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
        - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
          name: Run tests
          command: npm run test

workflows:
  build-test:
    jobs:
      - request-approval
      - build
          filters:
            branches:
              only:
                - beta
      - test
          