version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - node/install-packages:
          check-cache: detect
      - run:
          name: build
          command:  "yarn run build"
  test:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - node/install-packages:
          check-cache: detect
      - run:
          name: Run tests
          command: yarn run test

workflows:
  build-test-approval-deploy:
    jobs:
      - build
      - test          